"""empty message

Revision ID: 7274dd3f6a80
Revises: e6879c778b6c
Create Date: 2017-09-26 19:16:21.488010

"""

# revision identifiers, used by Alembic.
revision = '7274dd3f6a80'
down_revision = 'e6879c778b6c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'is_auth',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('bill', 'paid',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('mailbox', sa.Column('public_slug', sa.String(length=100), nullable=True))
    op.alter_column('mailbox', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'mailbox', ['public_slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mailbox', type_='unique')
    op.alter_column('mailbox', 'is_public',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('mailbox', 'public_slug')
    op.alter_column('bill', 'paid',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('author', 'is_auth',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
