"""empty message

Revision ID: fbdd8d0baf7d
Revises: 26a74194e031
Create Date: 2017-09-23 09:31:25.534216

"""

# revision identifiers, used by Alembic.
revision = 'fbdd8d0baf7d'
down_revision = '26a74194e031'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('issuer', sa.String(length=80), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('bpay_code', sa.String(length=10), nullable=True),
    sa.Column('bpay_acc', sa.String(length=25), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailbox.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.alter_column('author', 'is_auth',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'is_auth',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_table('bill')
    op.drop_table('category')
    # ### end Alembic commands ###
